// keys.js
export const keys = [
  // Row 1
  { id: 0, label: '`', classNames: 'key' },
  { id: 1, label: '1', classNames: 'key' },
  { id: 2, label: '2', classNames: 'key' },
  { id: 3, label: '3', classNames: 'key' },
  { id: 4, label: '4', classNames: 'key' },
  { id: 5, label: '5', classNames: 'key' },
  { id: 6, label: '6', classNames: 'key' },
  { id: 7, label: '7', classNames: 'key' },
  { id: 8, label: '8', classNames: 'key' },
  { id: 9, label: '9', classNames: 'key' },
  { id: 10, label: '0', classNames: 'key' },
  { id: 11, label: '-', classNames: 'key' },
  { id: 12, label: '=', classNames: 'key' },
  { id: 13, label: 'Backspace', classNames: 'key key-wide' },

  // Row 2
  { id: 14, label: 'Tab', classNames: 'key key-wide' },
  { id: 15, label: 'Q', classNames: 'key' },
  { id: 16, label: 'W', classNames: 'key' },
  { id: 17, label: 'E', classNames: 'key' },
  { id: 18, label: 'R', classNames: 'key' },
  { id: 19, label: 'T', classNames: 'key' },
  { id: 20, label: 'Y', classNames: 'key' },
  { id: 21, label: 'U', classNames: 'key' },
  { id: 22, label: 'I', classNames: 'key' },
  { id: 23, label: 'O', classNames: 'key' },
  { id: 24, label: 'P', classNames: 'key' },
  { id: 25, label: '[', classNames: 'key' },
  { id: 26, label: ']', classNames: 'key' },
  { id: 27, label: '\\', classNames: 'key' },

  // Row 3
  { id: 28, label: 'Caps Lock', classNames: 'key key-wide' },
  { id: 29, label: 'A', classNames: 'key' },
  { id: 30, label: 'S', classNames: 'key' },
  { id: 31, label: 'D', classNames: 'key' },
  { id: 32, label: 'F', classNames: 'key' },
  { id: 33, label: 'G', classNames: 'key' },
  { id: 34, label: 'H', classNames: 'key' },
  { id: 35, label: 'J', classNames: 'key' },
  { id: 36, label: 'K', classNames: 'key' },
  { id: 37, label: 'L', classNames: 'key' },
  { id: 38, label: ';', classNames: 'key' },
  { id: 39, label: '\'', classNames: 'key' },
  { id: 40, label: 'Enter', classNames: 'key key-wide' },

  // Row 4
  { id: 41, label: 'Shift', classNames: 'key key-wide' },
  { id: 42, label: 'Z', classNames: 'key' },
  { id: 43, label: 'X', classNames: 'key' },
  { id: 44, label: 'C', classNames: 'key' },
  { id: 45, label: 'V', classNames: 'key' },
  { id: 46, label: 'B', classNames: 'key' },
  { id: 47, label: 'N', classNames: 'key' },
  { id: 48, label: 'M', classNames: 'key' },
  { id: 49, label: ',', classNames: 'key' },
  { id: 50, label: '.', classNames: 'key' },
  { id: 51, label: '/', classNames: 'key' },
  { id: 52, label: 'Shift', classNames: 'key key-wide' },

    // Row 5
  { id: 53, label: 'Ctrl', classNames: 'key key-wide' },
  { id: 54, label: 'Win', classNames: 'key key-wide' },
  { id: 55, label: 'Alt', classNames: 'key key-wide' },
  { id: 56, label: 'Space', classNames: 'key key-extra-wide' },
  { id: 57, label: 'Alt', classNames: 'key key-wide' },
  { id: 58, label: 'Win', classNames: 'key key-wide' },
  { id: 59, label: 'Menu', classNames: 'key key-wide' },
  { id: 60, label: 'Ctrl', classNames: 'key key-wide' },
];
